### ISSUE TITLE
How to upgrade ?

### ISSUE THREAD

**Issue by michaeleino** [nuclias-connect/connect#12]
is it OK, if i'm running the old docker images marked **latest** to upgrade to the new images 1.2.0 ??

![Screenshot from 2022-04-10 15-57-14](https://user-images.githubusercontent.com/6287237/162622620-dbfd2b2f-10ee-4c5b-b23a-cb2c756c8e03.png)

is there a guide or a how to, is there any checks or a data migration for that ? or just stop and start with the new image ?

**Comment by michaeleino** [comment]
any one will volunteer to answer this basic question?

**Comment by ZhongJunJimmy** [comment]
@michaeleino yes

**Comment by michaeleino** [comment]
> @michaeleino yes

Yes what ?

**Comment by ZhongJunJimmy** [comment]
@michaeleino  Sorry, I misunderstood.
You can access following URL "https://download.nuclias.com/".
Following the description "Download Nuclias Connect for Linux"/ "Docker Hub Installation".
